from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('house_count', models.IntegerField(default=0)),
                ('avg_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('community_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'city', 'managed': False},
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('house_count', models.IntegerField(default=0)),
                ('avg_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_unit_price', models.IntegerField(blank=True, null=True)),
                ('min_unit_price', models.IntegerField(blank=True, null=True)),
                ('community_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'district', 'managed': False},
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('house_count', models.IntegerField(default=0)),
                ('avg_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'community', 'managed': False},
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='地区')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='房源链接')),
                ('mingcheng', models.CharField(blank=True, max_length=200, null=True, verbose_name='小区名称')),
                ('quyu', models.CharField(blank=True, max_length=200, null=True, verbose_name='所在区域')),
                ('huxing', models.CharField(blank=True, max_length=100, null=True, verbose_name='房屋户型')),
                ('louceng', models.CharField(blank=True, max_length=100, null=True, verbose_name='所在楼层')),
                ('mianji', models.CharField(blank=True, max_length=50, null=True, verbose_name='建筑面积')),
                ('huxingjiegou', models.CharField(blank=True, max_length=50, null=True, verbose_name='户型结构')),
                ('chaoxiang', models.CharField(blank=True, max_length=50, null=True, verbose_name='房屋朝向')),
                ('jianzhujiegou', models.CharField(blank=True, max_length=50, null=True, verbose_name='建筑结构')),
                ('zhuangxiu', models.CharField(blank=True, max_length=50, null=True, verbose_name='装修情况')),
                ('tihu', models.CharField(blank=True, max_length=50, null=True, verbose_name='梯户比例')),
                ('shijian', models.CharField(blank=True, max_length=50, null=True, verbose_name='挂牌时间')),
                ('quanshu', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易权属')),
                ('diya', models.CharField(blank=True, max_length=200, null=True, verbose_name='抵押信息')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='总价(万元)')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='单价(元/平方米)')),
                ('jingdu', models.CharField(blank=True, max_length=50, null=True, verbose_name='经度')),
                ('weidu', models.CharField(blank=True, max_length=50, null=True, verbose_name='纬度')),
                ('maidian', models.TextField(blank=True, null=True, verbose_name='核心卖点')),
                ('jieshao', models.TextField(blank=True, null=True, verbose_name='小区介绍')),
                ('huxingjieshao', models.TextField(blank=True, null=True, verbose_name='户型介绍')),
                ('jiaotong', models.TextField(blank=True, null=True, verbose_name='交通出行')),
                ('mianji_group', models.CharField(blank=True, max_length=20, null=True, verbose_name='面积分组')),
            ],
            options={'db_table': 'house_info', 'managed': False, 'verbose_name': '房源', 'verbose_name_plural': '房源'},
        ),
        migrations.CreateModel(
            name='CityStat',
            fields=[
                ('city', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('house_count', models.IntegerField(default=0)),
                ('community_count', models.IntegerField(default=0)),
                ('avg_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'house_city_stat', 'managed': False},
        ),
        migrations.CreateModel(
            name='RegionStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('house_count', models.IntegerField(default=0)),
                ('community_count', models.IntegerField(default=0)),
                ('avg_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_unit_price', models.IntegerField(blank=True, null=True)),
                ('min_unit_price', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'house_region_stat', 'managed': False},
        ),
        migrations.CreateModel(
            name='LayoutStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('layout_name', models.CharField(max_length=100)),
                ('house_count', models.IntegerField(default=0)),
                ('avg_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'house_layout_stat', 'managed': False},
        ),
        migrations.CreateModel(
            name='DecorationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('decoration_name', models.CharField(max_length=50)),
                ('house_count', models.IntegerField(default=0)),
                ('avg_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'house_decoration_stat', 'managed': False},
        ),
    ]
